from dotenv import load_dotenv
import os
import mysql.connector
from groq import Groq
import re

load_dotenv()

# Prompt do agente
system_prompt = """You are an intelligent SQL Agent capable of analyzing complex Google Ads data stored in a MySQL database. Your primary goal is to retrieve insightful information based on user questions using the minimum number of actions and queries possible.

The database contains the following tables relevant to Google Ads, with each table described alongside its columns and purpose:

- google_ads_campaigns: Contains data about advertising campaigns.
  - Columns:
    - campaign_id: Unique identifier for the campaign.
    - campaign_name: The name of the campaign.
    - start_date: Campaign start date.
    - end_date: Campaign end date.
    - campaign_status: The campaign's current status (active, paused, completed).

- google_ads_ad_sets: Groups of ads associated with a campaign.
  - Columns:
    - ad_set_id: Unique identifier for the ad set.
    - campaign_id: ID of the associated campaign.
    - ad_group_name: The name of the ad group.
    - target_audience: The target audience for the ad set.

- google_ads_ad_details: Details about individual ads.
  - Columns:
    - ad_id: Unique identifier for the ad.
    - ad_set_id: ID of the associated ad set.
    - ad_name: Name of the ad.
    - ad_type: Type of the ad (e.g., responsive_search_ad, text_ad, video_ad).
    - ad_strength: Strength of the ad (e.g., poor, average, good, excellent).
    - keyword_info: Keywords associated with the ad.

- google_ads_performance: Contains performance metrics for ads over time.
  - Columns:
    - performance_id: Unique identifier for the performance record.
    - ad_id: ID of the associated ad.
    - date: Date of the performance record.
    - ctr: Click-through rate.
    - cpm: Cost per thousand impressions.
    - cpc: Cost per click.
    - impressions: Total number of impressions.
    - interactions: Total number of interactions.
    - interaction_rate: Interaction rate.
    - cost_spent: Total cost spent.
    - clicks: Total number of clicks.

- google_ads_conversions: Tracks ad conversions.
  - Columns:
    - conversion_id: Unique identifier for the conversion record.
    - ad_id: ID of the associated ad.
    - conversions: Total number of conversions.
    - cost_per_conversion: Cost per conversion.
    - conversion_date: Date of the conversion.
    - conversion_value: Total value generated by conversions.

Guidelines:
1. Efficiency: Minimize the number of SQL queries by planning them effectively. Use a single query to retrieve as much relevant data as possible.
2. Query Constraints:
   - Use LIMIT 20 on all SELECT queries to prevent retrieving excessive data.
   - Never modify the database (e.g., through UPDATE, DELETE, or INSERT).
3. User Interaction: Use Thought, Action, PAUSE, and Observation to guide your reasoning and interact with the user.
4. Abstraction: Avoid exposing table names or database structure directly to the user. Provide user-friendly answers instead.

Workflow:
- Thought: Analyze the user's question and determine the data needed.
- Action: Execute a query or request user feedback.
- PAUSE: Stop and wait for the query's result or user input.
- Observation: Use the retrieved data or feedback to refine your reasoning.
- Answer: Provide the final response to the user's question.

Your available actions are:

- Query SQL Database:
  Call this action using the following exact format:
  Action: query_sql_database: SELECT column_name FROM table_name WHERE condition LIMIT 20
  Do not include additional formatting such as quotes or code blocks around the query.

Example:
Action: query_sql_database: SELECT campaign_name, AVG(ctr) FROM google_ads_campaigns JOIN google_ads_performance ON google_ads_campaigns.campaign_id = google_ads_performance.campaign_id WHERE google_ads_performance.date >= DATE_SUB(CURDATE(), INTERVAL 6 MONTH) GROUP BY campaign_name ORDER BY AVG(ctr) DESC LIMIT 1


Example of a user interaction cycle:
User Query:
"Which of my Google Ads campaigns performed the best in the last 6 months?"

Agent Response:
Thought: I need to determine the campaign with the best performance based on metrics like CTR or conversions in the last 6 months.
Action: query_sql_database: SELECT campaign_name, AVG(ctr) AS avg_ctr FROM google_ads_campaigns JOIN google_ads_performance ON google_ads_campaigns.campaign_id = google_ads_performance.campaign_id WHERE google_ads_performance.date >= DATE_SUB(CURDATE(), INTERVAL 6 MONTH) GROUP BY campaign_name ORDER BY avg_ctr DESC LIMIT 1
PAUSE
Observation: The campaign "Boost Your Reach" has the highest CTR of 15%.
Answer: Your best-performing campaign in the last 6 months is "Boost Your Reach" with an average CTR of 15%.

Now it's your turn:
""".strip()

# Cliente Groq
client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

class CodeEvaluatorAgent:
    def __init__(self, client, system_prompt: str):
        self.client = client
        self.messages = [{"role": "system", "content": system_prompt}]
    
    def __call__(self, user_input):
        self.messages.append({"role": "user", "content": user_input})
        result = self._execute()
        self.messages.append({"role": "assistant", "content": result})
        return result
    
    def _execute(self):
        completion = self.client.chat.completions.create(
            model="llama3-70b-8192",
            messages=self.messages
        )
        return completion.choices[0].message.content

# Função para executar consultas SQL seguras
def query_sql_database(query: str) -> str:
    """Executa uma consulta SQL segura que não altera o banco de dados."""
    prohibited_keywords = ["UPDATE", "DELETE", "CREATE", "DROP", "ALTER", "INSERT"]

    if any(keyword in query.upper() for keyword in prohibited_keywords):
        return "Error: Query contains prohibited operations."
    
    try:
        # Conexão com o banco de dados MySQL
        conn = mysql.connector.connect(
            host=os.environ.get("DB_HOST"),
            user=os.environ.get("DB_USER"),
            password=os.environ.get("DB_PASSWORD"),
            database=os.environ.get("DB_NAME")
        )
        cursor = conn.cursor()
        cursor.execute(query)
        rows = cursor.fetchall()
        conn.close()

        # Retorna os resultados formatados
        return "\n".join(str(row) for row in rows) if rows else "No results found."
    except Exception as e:
        return f"Error executing query: {e}"

# Função para solicitar feedback
def ask_for_feedback(prompt: str) -> str:
    feedback = input(f"[Feedback Request] {prompt}")
    return feedback

# Extrai ações do resultado
def extract_action(result: str) -> dict:
    action_match = re.search(r"Action: ([a-z_]+): (.+)", result)
    if action_match:
        return {'tool': action_match.group(1), 'arg': action_match.group(2)}
    return {'tool': '', 'arg': ''}

# Loop principal
def loop(max_iterations=10, user_question: str = ""):
    # Inicialize o agente
    agent = CodeEvaluatorAgent(client=client, system_prompt=system_prompt)

    # Dicionário de ferramentas
    tools = {
        "ask_for_feedback": ask_for_feedback,
        "query_sql_database": query_sql_database,
    }

    next_prompt = user_question
    i = 0

    while i < max_iterations:
        i += 1
        result = agent(next_prompt)
        print(f"\n[Agent Thought]: {result}")

        if "PAUSE" in result and "Action" in result:
            # Extraia a ação e os argumentos
            action_info = extract_action(result)
            chosen_tool = action_info['tool']
            arg = action_info['arg']

            # Verifique se a ação está no dicionário de ferramentas
            if chosen_tool in tools:
                result_tool = tools[chosen_tool](arg)
                next_prompt = f"Observation: {result_tool}"
            else:
                next_prompt = "Observation: Tool not found"

            print(f"\n[Agent Observation]: {next_prompt}")
            continue

        if "Answer" in result:
            print(f"\n[Final Answer]: {result}")
            break

# Exemplo de uso natural
loop(10, 'Qual dos meus anúncios do Google teve a pior variação em  taxa de cliques em um periodo de um mês nos últimos 6 meses?')
